name: diabetesrisk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Ensure SDK version is correctly specified

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.0  # For downloading CSV files
  path_provider: ^2.0.15       # Access local file directories for saving CSV
  intl: ^0.18.0
  file_picker: ^5.5.0
  dio: ^5.3.2
  http: ^0.13.6  # Updated version of the http package
  cupertino_icons: ^1.0.5  # Standard icons package for iOS
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/diabetesrisk.png" # Correct icon path

flutter:
  uses-material-design: true

  assets:
    - assets/diabetes1.png
    - assets/login.jpg
    - assets/dashboard.png
    - assets/addpatient.jpg
    - assets/CT-scan-machine.jpg
    - assets/risk.png
    - assets/diabetesrisk.png
